### ISSUE TITLE
Issue screenshots

### ISSUE THREAD

**Issue by SystaxError** [revanced/revanced-website#131]
![Screenshot_2023-06-22-01-20-05-097_com brave browser](https://github.com/revanced/revanced-website/assets/79525322/a3e34f70-f494-40b8-b1b9-fb7ec5c140ae)
No UI for the buttons
![Screenshot_2023-06-22-01-20-10-954_com brave browser](https://github.com/revanced/revanced-website/assets/79525322/3784b23a-b072-4349-ac98-631ac6abaebb)
Missing patches page

**Comment by Ushie** [comment]
Do you have an adblocking software? does this issue happen on Chrome

**Comment by oSumAtrIX** [comment]
I can reproduce. Maybe related:

## Failed run: <https://github.com/revanced/revanced-website/actions/runs/5329334447>

 ## Last working deployment by the Cloudflare Pages application for GitHub: <https://bf4ee9fb.revanced.pages.dev/>

The image may hint the issue. The previews were created by workflows that ran when triggered by a pull request. The source says `HEAD`.
The last production deployment says `main`, created by a workflow that ran on push to the `main` branch.

![image](https://github.com/revanced/revanced-website/assets/13122796/1e9fb82d-0ef6-439e-916b-ed83d3ee49e7)

Retrying the last deployment (production) gives this error with no logs:

![image](https://github.com/revanced/revanced-website/assets/13122796/d772d7b4-892b-4b59-8f18-4f1760c9c987)

This issue started, once I switched to using the action instead of the CloudFlare app to deploy. CloudFlare app deployments had proper source branch names such as `dev` or `main` but `HEAD` only started to appear, after I switched to the action

**Comment by oSumAtrIX** [comment]
Rollbacked deployment to last working version
